//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5GroupSln.SEOService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SEOService.IRequiredServices")]
    public interface IRequiredServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequiredServices/WordFilter", ReplyAction="http://tempuri.org/IRequiredServices/WordFilterResponse")]
        string WordFilter(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequiredServices/WordFilter", ReplyAction="http://tempuri.org/IRequiredServices/WordFilterResponse")]
        System.Threading.Tasks.Task<string> WordFilterAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequiredServices/Stemming", ReplyAction="http://tempuri.org/IRequiredServices/StemmingResponse")]
        string Stemming(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequiredServices/Stemming", ReplyAction="http://tempuri.org/IRequiredServices/StemmingResponse")]
        System.Threading.Tasks.Task<string> StemmingAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequiredServicesChannel : Project5GroupSln.SEOService.IRequiredServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequiredServicesClient : System.ServiceModel.ClientBase<Project5GroupSln.SEOService.IRequiredServices>, Project5GroupSln.SEOService.IRequiredServices {
        
        public RequiredServicesClient() {
        }
        
        public RequiredServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequiredServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequiredServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequiredServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WordFilter(string str) {
            return base.Channel.WordFilter(str);
        }
        
        public System.Threading.Tasks.Task<string> WordFilterAsync(string str) {
            return base.Channel.WordFilterAsync(str);
        }
        
        public string Stemming(string str) {
            return base.Channel.Stemming(str);
        }
        
        public System.Threading.Tasks.Task<string> StemmingAsync(string str) {
            return base.Channel.StemmingAsync(str);
        }
    }
}
